### ISSUE TITLE
 open source

### ISSUE THREAD

**Issue by ZhenboZhao77** [zhaozeyang108/Oriented-DETR#4]
Could you please provide the specific date when the code for the paper will be released as open source?

**Comment by zhaozeyang108** [comment]
抱歉啊，最近秋招身心俱疲加上前段时间实验室服务器崩了导致一直没开源。秋招结束了就搞起来。不过方法整体很简单，可以先在自己的detector上复现下/*回归对象*/和/*损失函数*/。我最近让师弟在yolov8-obb上复现，比baseline高了很多（map50高一个点左右，map75高五个点左右）

**Comment by ZhenboZhao77** [comment]
辛苦，期待开源！

**Comment by cowqer** [comment]
期待开源+1
