### ISSUE TITLE
failed to install panopticapi

### ISSUE THREAD

**Issue by Yiliud** [zhaozeyang108/Oriented-DETR#6]
当我执行pip install -r requirements.txt这一步时报错
![fa7b68cf2c607562642a66dfdc51cac](https://github.com/user-attachments/assets/861407bf-30ec-4eb0-a03e-07b731464306)
我不明白为什么会出现这个问题，能否寻求您的帮助，非常感谢

**Comment by zhaozeyang108** [comment]
把这个包删了，应该不会用到。

**Comment by Yiliud** [comment]
> 把这个包删了，应该不会用到。

好的好的谢谢
