### ISSUE TITLE
Problems with visualization

### ISSUE THREAD

**Issue by nico4311** [zhaozeyang108/Oriented-DETR#7]
![P0009__1__0___0](https://github.com/user-attachments/assets/f4af31e9-647f-4fb4-b70a-91765c1d0dba)
![P0009__1__0___824](https://github.com/user-attachments/assets/b9982800-f270-45cb-a119-5ed37aabca4b)
![P0015__1__0___0](https://github.com/user-attachments/assets/064c295d-da36-4d2c-9812-9f67048fd9ed)

Hello, the methodology and idea of your paper is great, I have encountered the following problem in reproducing the code.
The visualization of the test task using the following configuration shows a lot of extra bounding boxes and the color of the bounding boxes is mostly inconsistent for detecting objects of the same category. I observed that your code selects the first 400 objects with high confidence scores for each test image for orientation detection and filters out some of the bounding boxes using inf_conf=0.005. However, the above phenomenon occurs during the test task, maybe I'm using it in a wrong way or your visualization code is not in engine.py, hope you can answer this question.

The instructions are as follows:

--local_rank=0
--output_dir
eva/infernece_swint_ss_eval
-c
config/dota/4scale_swint_ss_dota.py
--coco_path
datasets/DOTAV1_0_COCO
--dataset_file
dota
--pretrain_model_path
pretrained_model/swin_t_dota_ss.pth
--test

The code to visualize the process is the following:
 for img_id, predict in output_per_image.items():
        img_info = base_ds.loadImgs(img_id)[0]
        # 获取图像的文件名和路径
        img_filename = img_info['file_name']
        img_path = os.path.join(args.coco_path, "test2017", img_filename)  # 你的图像目录
        # 读取和显示图像
        img = cv2.imread(img_path)
        categories = predict[0]
        polys = predict[2]
        points = predict[3]
        for cls, poly, pts in zip(categories, polys, points):
            poly = poly.reshape(-1, 1, 2).astype(int)
            img = cv2.polylines(img, [poly], True, color_table[cls-1], thickness=2)
        img_name = os.path.join(visdir, img_filename)
        cv2.imwrite(img_name, img)
        cout += 1
        if cout > 200:
            break

color_table={0:(41,42,165),1:(107, 183, 189), 2:(0,255,0), 3: (0,0,255), 4:(255, 43,138),
             5:(44,146,247), 6:(254,0,255), 7:(255,255,1), 8:(194,193,255), 9:(153,51,0),
             10:(207,249,254), 11:(133, 135, 0), 12:(1, 255, 255), 13:(118,115,147), 14:(255,0,0)}

**Comment by zhaozeyang108** [comment]
> ![P0009__1__0___0](https://private-user-images.githubusercontent.com/96479590/396312997-f4af31e9-647f-4fb4-b70a-91765c1d0dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjIzMjQsIm5iZiI6MTczNDUyMjAyNCwicGF0aCI6Ii85NjQ3OTU5MC8zOTYzMTI5OTctZjRhZjMxZTktNjQ3Zi00ZmI0LWI3MGEtOTE3NjVjMWQwZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExNDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjgxZjliMTI2M2FmNjQwMmVlMTViMjM0YWNkMTY2YzIzMGQzOTA4YTI4ODYxYWQyMzliYzM3YzExYThkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RPGiC1WThLF5OqzklgVbfTuaHjiWKtL9VT1veODfGTQ) ![P0009__1__0___824](https://private-user-images.githubusercontent.com/96479590/396313016-b9982800-f270-45cb-a119-5ed37aabca4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjIzMjQsIm5iZiI6MTczNDUyMjAyNCwicGF0aCI6Ii85NjQ3OTU5MC8zOTYzMTMwMTYtYjk5ODI4MDAtZjI3MC00NWNiLWExMTktNWVkMzdhYWJjYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExNDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MWRjNjZjODYyMzNlZmY4NmI4ZjQ5MjhhZjc5ZGYyZjIzNjRiZDQ1MTA1YmUzMWY4OTk4MWE0ZTVlZDNhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8YnWnOR1qcMxsnjzjLC1WuMBNBbamGgu_OC90hdS5-k) ![P0015__1__0___0](https://private-user-images.githubusercontent.com/96479590/396313061-064c295d-da36-4d2c-9812-9f67048fd9ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjIzMjQsIm5iZiI6MTczNDUyMjAyNCwicGF0aCI6Ii85NjQ3OTU5MC8zOTYzMTMwNjEtMDY0YzI5NWQtZGEzNi00ZDJjLTk4MTItOWY2NzA0OGZkOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExNDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYTU2ODkzMThkNDZhM2IxOGQzYzUyMzUyZmVlMDFjNWFhMmRkZmZmOTJhZDE2YjRkZmY1NWMwOTJmMTM3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NWJTnGObLUEemKoLw_dg0wBR2c6MHeKPoR2nXHd6_pE)
> 
> Hello, the methodology and idea of your paper is great, I have encountered the following problem in reproducing the code. The visualization of the test task using the following configuration shows a lot of extra bounding boxes and the color of the bounding boxes is mostly inconsistent for detecting objects of the same category. I observed that your code selects the first 400 objects with high confidence scores for each test image for orientation detection and filters out some of the bounding boxes using inf_conf=0.005. However, the above phenomenon occurs during the test task, maybe I'm using it in a wrong way or your visualization code is not in engine.py, hope you can answer this question.
> 
> The instructions are as follows:
> 
> --local_rank=0 --output_dir eva/infernece_swint_ss_eval -c config/dota/4scale_swint_ss_dota.py --coco_path datasets/DOTAV1_0_COCO --dataset_file dota --pretrain_model_path pretrained_model/swin_t_dota_ss.pth --test
> 
> The code to visualize the process is the following: for img_id, predict in output_per_image.items(): img_info = base_ds.loadImgs(img_id)[0] # 获取图像的文件名和路径 img_filename = img_info['file_name'] img_path = os.path.join(args.coco_path, "test2017", img_filename) # 你的图像目录 # 读取和显示图像 img = cv2.imread(img_path) categories = predict[0] polys = predict[2] points = predict[3] for cls, poly, pts in zip(categories, polys, points): poly = poly.reshape(-1, 1, 2).astype(int) img = cv2.polylines(img, [poly], True, color_table[cls-1], thickness=2) img_name = os.path.join(visdir, img_filename) cv2.imwrite(img_name, img) cout += 1 if cout > 200: break
> 
> color_table={0:(41,42,165),1:(107, 183, 189), 2:(0,255,0), 3: (0,0,255), 4:(255, 43,138), 5:(44,146,247), 6:(254,0,255), 7:(255,255,1), 8:(194,193,255), 9:(153,51,0), 10:(207,249,254), 11:(133, 135, 0), 12:(1, 255, 255), 13:(118,115,147), 14:(255,0,0)}

The confidence threshold is set relatively low to more accurately calculate the CoCo mAP metric (to prevent the tail of the PR curve area from not being counted). In actual applications, it can be adjusted higher. Theoretically, a setting of 0.15 will not result in many  redundant bounding boxes. This setting is the "inf_conf" in the configuration file.
